import os
from os import getenv
from dotenv import load_dotenv

load_dotenv()
admins = {}
SESSION_NAME = getenv("SESSION_NAME", "session")
BOT_TOKEN = getenv("BOT_TOKEN")
BOT_NAME = getenv("BOT_NAME")
API_ID = int(getenv("API_ID"))
API_HASH = getenv("API_HASH")
MONGODB_URL = getenv("MONGODB_URL")
OWNER_NAME = getenv("OWNER_NAME")
ALIVE_NAME = getenv("ALIVE_NAME")
BOT_PHOTO = getenv("BOT_PHOTO")
DEV_PHOTO = getenv("DEV_PHOTO")
DEV_NAME = getenv("DEV_NAME")
BOT_USERNAME = getenv("BOT_USERNAME")
UPSTREAM_REPO = getenv("UPSTREAM_REPO")
UPSTREAM_BRANCH = getenv("UPSTREM_BRANCH", "main")
ASSISTANT_NAME = getenv("ASSISTANT_NAME")
GROUP_SUPPORT = getenv("GROUP_SUPPORT", "xb_bk")
UPDATES_CHANNEL = getenv("UPDATES_CHANNEL", "xb_bp")
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "1939538780").split()))
COMMAND_PREFIXES = list(getenv("COMMAND_PREFIXES", "/ ! . ت م ا غ س ش ك").split())
ALIVE_IMG = getenv("ALIVE_IMG", "https://telegra.ph/file/4cbb70d2cbcef89687188.jpg")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "900"))
UPSTREAM_REPO = getenv("https://github.com/alfaransy/alazizy")
IMG_1 = getenv("IMG_1", "https://telegra.ph/file/cbefab50d720cd7cb5ca8.jpg")
IMG_2 = getenv("IMG_2", "https://telegra.ph/file/cbefab50d720cd7cb5ca8.jpg")
IMG_3 = getenv("IMG_3", "https://telegra.ph/file/cbefab50d720cd7cb5ca8.jpg")
IMG_4 = getenv("IMG_4", "https://telegra.ph/file/cbefab50d720cd7cb5ca8.jpg")
IMG_5 = getenv("IMG_5", "https://telegra.ph/file/cbefab50d720cd7cb5ca8.jpg")
